export {Dashboard} from  "./Dashboard"
export {DataAlternatif} from "./DataAlternatif"
export {DataHasilAkhir} from "./DataHasilAkhir"
export {DataKriteria} from "./DataKriteria"
export {DataPenilaian} from "./DataPenilaian"
export {DataPerhitungan} from "./DataPerhitungan"
export {DataSubKriteria} from "./DataSubKriteria" 
export {KelolaAdmin} from "./KelolaAdmin" 